# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='images/333.png', upload_to='images/upload/')),
                ('dianzan', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('type', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Pinglun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('Pinglun_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Pinglun')),
                ('photo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('type', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='pinglun',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.User'),
        ),
    ]
