# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-12 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20170411_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='dianzan',
            field=models.IntegerField(default=0),
        ),
    ]
