# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-13 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20170412_2115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=256)),
                ('dianzan', models.IntegerField(default=0)),
                ('time', models.CharField(max_length=32)),
                ('seenum', models.IntegerField(default=0)),
                ('content', models.CharField(max_length=256)),
            ],
        ),
    ]
